
############################################################
#
# Light Control 
#
############################################################


- alias: Dinning Light Control 
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d0001831c46
        click_type: single
  action:
      service: light.toggle
      entity_id:
         - light.hue_white_lamp_1
         - light.hue_white_lamp_2
