
############################################################
#
# Update Available Notification
#
############################################################


- alias: Update Available Notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: script.pushbullet_notify
      data: {"value1":"New HASS update is available. Please update!", "value2":""}
